name: umkm_digital_helper
description: "Aplikasi Warungku untuk mengelola bisnis kecil kecilan"

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ^3.9.2 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  cached_network_image: ^3.3.0 
  connectivity_plus: ^5.0.1 
  fl_chart: ^0.65.0

  #database
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.2.2

  #state management
  provider: ^6.1.5

  #menyimpan sesi login 
  shared_preferences: ^2.5.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

  
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_umkm.png      
    - assets/images/logo_apk.png
    - assets/produk/matcha_latte.jpg   
    - assets/produk/kopi_susu_gula_aren.jpg 
    - assets/produk/kopi_americano.jpg 
    - assets/produk/es_teh.jpg
    - assets/produk/sate.jpg
    - assets/produk/bakso.jpeg
    - assets/produk/nugget.jpg
    - assets/produk/kukis.jpg
    - assets/produk/v60.jpg

# Konfigurasi auto generate app icons
flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo_apk.png"
  adaptive_icon_foreground: "assets/images/logo_apk.png"
  adaptive_icon_background: "#FFFFFF"

